<div id="desktop">
    <header>
    	<div id="logo">
    	    <img src="content/images/desktop/logo.png" alt="Logo" />
        </div>
        
        <h1> An experience inside beautiful buildings in Ghent </h1>
    </header>
       
    <div id="backgroundimg"></div>
    
    <div id="backgroundeen">
        <div class="content-desktop">
       	    <section id="what">
       	        <article>
                	<div class="icon" id="whaticon"><img src="content/images/desktop/What_icon.png" alt="What" /></div>
                    <p>Ghent has all kinds of beautiful buildings, but sometimes they aren’t accessible for visitors. Don’t you want to know what’s behind the walls? </p><p id="withapp">With the app you can scan the QR-codes in front of various buildings troughout Ghent and get a short video of what’s inside.</p> <aside>Go ahead, download and scan them all.</aside>					
                </article>
                 
                <article id="where">
                    	<div class="icon" id="whereicon"><img src="content/images/desktop/Where_icon.png" alt="Where" /></div>
                        <p id="map">Go to the map to find all the available buildings and find your way their. An excellent tool to check out the whole city. </p>
                    	<a href="Desktop/Map">
                            <img src="content/images/desktop/map_preview.png" alt"Map preview" />
                            <div id="zoom">
                                <img src="content/images/desktop/zoom.png" alt="Zoom" />
                            </div>
                        </a>
                </article>  
            </section>
            
            <section id="download">
          		<div id="downloadicon">            	
                    <img src="content/images/desktop/download_icon.png" alt="Download" />
                </div>
                
                <article id="left" class="download">
                	<img src="content/images/desktop/video_preview.png" alt="Video" />
                    <p>
                        Sniff the atmosphere from the inside by <em>watching the video's</em>.
                    </p>
                </article>
                 
                <article id="midright" class="download">
                    <div id="mid">
                        <img src="content/images/desktop/menu_preview.png" alt="Menu" />
                        <p>
                            Get a <em>personal home screen</em> with a Must See recomendation list, your own favorites, Look Laters and a list of all the buildings you've already scanned.
                        </p>
                    </div>
                   
                    <div id="right">
                        <div id="scan_preview">
                   	        <img src="content/images/desktop/scan_preview.png" alt="Scan" /> 
                        </div>
                        <p>
                            <em>Scan</em> all the QR-codes from within the app.
                        </p>
                    </div>
                 </article>
            </section>         
        </div>
    </div>
       
    <div id="backgroundtwee">
        <div class="content-desktop">
            <article id="credits">
            	<div class="footericon" id="ink">
       	    	   <img src="content/images/desktop/ink.png" class="ink" />
                </div>
                
                <div class="creditsblock" id="creditsblockeen">       
                    <p class="left">Developed by:</p>
                    
                    <div class="right">                
                        <li>Lieven Benoot </li>
                        <li>Sam Verschueren </li>
                    </div> 
                    
                    <p class="left" id="design">Designed by:</p>
                    
                    <div class="right" id="nicolas">
                    	<li>Nicolas Dierck </li> 
                    </div>
                    
                    <div class="clear"></div> 
                </div>
    
    
                <div class="creditsblock">                                          
                        <p class="left" id="filmed"> Concept and director:</p>
                        
                        <div class="right" id="peter">
                        	<li>Peter De Bock (Stad Gent)</li> 
                        </div>
                       
                        <div class="clear"></div>
                </div>
                
                <div class="creditsblock">    
                        <p id="code9000" class="full">Developed under the name of code9000 (#code9000) during iRail Summer of Code (#iSoc12) </p>
                        <div class="clear"></div>
                </div>
            </article>
         
            <article id="sponsor">
            	<div class="footericon">
                    <img src="content/images/desktop/hands.png" alt="Hands" />
                </div>
                
    			<div class="full" id="sponsors">                            
                       <a href="http://digipolis.be" target="_newtab"><img class="sponsorlogo" src="content/images/desktop/sponsors/digipolis.png" alt="Digipolis" /></a>
                       <a href="http://hello.irail.be/" target="_newtab"><img class="sponsorlogo" src="content/images/desktop/sponsors/iRail.png" alt="iRail" /></a>
                       <a href="http://gent.be" target="_newtab"><img class="sponsorlogo" src="content/images/desktop/sponsors/stadgent.png" alt="Stad Gent" /></a>
                       <a href="http://gent.be" target="_newtab"><img class="sponsorlogo" src="content/images/desktop/sponsors/gentzoveelstad.png" alt="Zoveel Stad" /></a>
            	</div>
            </article>        
        </div>
    </div>
</div>