<div class="page">
    <h1><?php echo $model->getName(); ?></h1>
    
    <table class="center">
    <tr>
        <td>Name:</td>
        <td><input type="text" name="name" value="<?php echo $model->getName(); ?>" /></td>
    </tr>
    <tr>
        <td>Category:</td>
        <td></td>
    </tr>
    <tr>
        <td>Adress:</td>
        <td><input type="text" name="adress" value="<?php echo $model->getAdress(); ?>" /></td>
    </tr>
    <tr>
        <td>Longitude:</td>
        <td><input type="text" name="longitude" value="<?php echo $model->getLongitude(); ?>" /> <a href="http://universimmedia.pagesperso-orange.fr/geo/loc.htm">Find</a></td>
    </tr>
    <tr>
        <td>Latitude:</td>
        <td><input type="text" name="latitude" value="<?php echo $model->getLatitude(); ?>" /></td>
    </tr>
    <tr>
        <td>Movie:</td>
        <td>
            <select name="category">
            <?php
               
            ?>
            </select>
        </td>
    </tr>
    <tr>
        <td>Description:</td>
        <td><textarea name="description" rows="5" cols="30"><?php echo $model->getDescription(); ?></textarea></td>
    </tr>
    <tr>
        <td></td>
        <td><input type="submit" value="opslaan" /></td>
    </tr>
    </table>
</div>
