<div class="page" id="edit">
    <h1><?php echo $model->getBuildingViewModel()->getName(); ?></h1>
    
    <form action="Admin/Edit" method="post">
        <input type="hidden" name="id" value="<?php echo $model->getBuildingViewModel()->getId(); ?>" />
        
        <table class="center">
        <tr>
            <td>Name:</td>
            <td><input type="text" name="name" value="<?php echo $model->getBuildingViewModel()->getName(); ?>" /></td>
        </tr>
        <tr>
            <td>Category:</td>
            <td>
                <select name="category">
                <?php
                   foreach($model->getCategoryViewModels() as $categoryViewModel) {
                       $select = '';
                       
                       if($model->getBuildingViewModel()->getCategory() == $categoryViewModel->getName()) {
                           $select = 'selected="selected"';
                       }
                       
                       echo '<option value="' . $categoryViewModel->getId() . '"' . $select . '>' . $categoryViewModel->getName() . '</option>';
                   }
                ?>
                </select>
            </td>
        </tr>
        <tr>
            <td>Infolink:</td>
            <td><input type="text" name="infolink" value="<?php echo $model->getBuildingViewModel()->getInfoLink(); ?>"</td>
        </tr>
        <tr>
            <td>Adress:</td>
            <td><input type="text" name="adress" value="<?php echo $model->getBuildingViewModel()->getAdress(); ?>" /></td>
        </tr>
        <tr>
            <td>Longitude:</td>
            <td><input type="text" name="longitude" value="<?php echo $model->getBuildingViewModel()->getLongitude(); ?>" /> <a href="http://universimmedia.pagesperso-orange.fr/geo/loc.htm">Find</a></td>
        </tr>
        <tr>
            <td>Latitude:</td>
            <td><input type="text" name="latitude" value="<?php echo $model->getBuildingViewModel()->getLatitude(); ?>" /></td>
        </tr>
        <tr>
            <td>Movie:</td>
            <td>
            <select name="movie">
                <option value=""></option>
                <?php
                   foreach($model->getMovieViewModels() as $movieViewModel) {
                       $select = '';
                       
                       if($model->getBuildingViewModel()->getMovie() == $movieViewModel->getFileName()) {
                           $select = 'selected="selected"';
                       }
                       
                       echo '<option value="' . $movieViewModel->getId() . '"' . $select . '>' . $movieViewModel->getFileName() . '</option>';
                   }
                ?>
                </select>    
            </td>
        </tr>
        <tr>
            <td>Description:</td>
            <td><textarea name="description" rows="5" cols="30"><?php echo $model->getBuildingViewModel()->getDescription(); ?></textarea></td>
        </tr>
        <tr>
            <td></td>
            <td>
                <input type="submit" name="action" value="Save" />
                <input type="submit" name="action" value="Cancel" />
            </td>
        </tr>
        </table>
    </form>
</div>
