<div class="page" id="edit">
    
    <?php
        $buildingViewModel = $model->getBuildingViewModel();
    ?>
    
    <h1><?php echo isset($buildingViewModel)?$buildingViewModel->getName():'New building'; ?></h1>
    
    <form action="Admin/Edit" method="post">
        <input type="hidden" name="id" value="<?php echo isset($buildingViewModel)?$buildingViewModel->getId():'0'; ?>" />
        
        <table class="center">
        <tr>
            <td>Name:</td>
            <td><input type="text" name="name" value="<?php echo isset($buildingViewModel)?$buildingViewModel->getName():''; ?>" /></td>
        </tr>
        <tr>
            <td>Category:</td>
            <td>
                <select name="category">
                <?php
                   foreach($model->getCategoryViewModels() as $categoryViewModel) {
                       $select = '';
                       
                       if(isset($buildingViewModel) && $buildingViewModel->getCategory() == $categoryViewModel->getName()) {
                           $select = 'selected="selected"';
                       }
                       
                       echo '<option value="' . $categoryViewModel->getId() . '"' . $select . '>' . $categoryViewModel->getName() . '</option>';
                   }
                ?>
                </select>
            </td>
        </tr>
        <tr>
            <td>Infolink:</td>
            <td><input type="text" name="infolink" value="<?php echo isset($buildingViewModel)?$buildingViewModel->getInfoLink():''; ?>"</td>
        </tr>
        <tr>
            <td>Adress:</td>
            <td><input type="text" name="adress" value="<?php echo isset($buildingViewModel)?$buildingViewModel->getAdress():''; ?>" /></td>
        </tr>
        <tr>
            <td>Longitude:</td>
            <td><input type="text" name="longitude" value="<?php echo isset($buildingViewModel)?$buildingViewModel->getLongitude():''; ?>" /> <a href="http://universimmedia.pagesperso-orange.fr/geo/loc.htm">Find</a></td>
        </tr>
        <tr>
            <td>Latitude:</td>
            <td><input type="text" name="latitude" value="<?php echo isset($buildingViewModel)?$buildingViewModel->getLatitude():''; ?>" /></td>
        </tr>
        <tr>
            <td>Movie:</td>
            <td>
            <select name="movie">
                <option value=""></option>
                <?php
                   foreach($model->getMovieViewModels() as $movieViewModel) {
                       $select = '';
                       
                       if(isset($buildingViewModel) && $buildingViewModel->getMovie() == $movieViewModel->getFileName()) {
                           $select = 'selected="selected"';
                       }
                       
                       echo '<option value="' . $movieViewModel->getId() . '"' . $select . '>' . $movieViewModel->getFileName() . '</option>';
                   }
                ?>
                </select>    
            </td>
        </tr>
        <tr>
            <td>Description:</td>
            <td><textarea name="description" rows="5" cols="30"><?php echo isset($buildingViewModel)?$buildingViewModel->getDescription():''; ?></textarea></td>
        </tr>
        <tr>
            <td></td>
            <td>
                <input type="submit" name="action" value="Save" />
                <input type="submit" name="action" value="Cancel" />
            </td>
        </tr>
        </table>
    </form>
</div>
