<div id="admin" class="page">

    <p class="logout">
        <?php
            echo 'Welcome ' . $viewData['user'];
        ?>
        (<a href="Logon/Logout">Logout</a>)
    </p>
    
    <h1>Admin page</h1>
   
    <table class="center">
    <tr>
        <th>Name</th>
        <th>Category</th>
        <th>Info</th>
        <th>Adress</th>
        <th>Longitude</th>
        <th>Latitude</th>
        <th>Movie</th>
        <th>QR Code</th>
        <th></th>
    </tr>
    <?php
    $i=0;
    foreach($model as $building) {
        $class = '';
        if((++$i)%2==0) {
            $class = ' class="odd"';
        }
        
        echo '<tr' . $class . '>';
        echo '<td>' . $building->getName() . '</td>';
        echo '<td>' . $building->getCategory() . '</td>';
        echo '<td>' . ($building->getInfoLink()==''?'':'<a href="' . $building->getInfoLink() . '">Link</a>') . '</td>';
        echo '<td>' . $building->getAdress() . '</td>';
        echo '<td>' . $building->getLongitude() . '</td>';
        echo '<td>' . $building->getLatitude() . '</td>';
        echo '<td>' . $building->getMovie() . '</td>';
        echo '<td>' . ($building->getToken()==''?'':'<a href="Admin/GenerateQR/' . $building->getToken() . '">Generate</a>') . '</td>';
        echo '<td><a href="Admin/Edit/' . $building->getId() . '"><img src="content/images/admin/edit.png" alt="Edit" /></a> <a href="Admin/Delete/' . $building->getId() . '"><img src="content/images/admin/delete.png" alt="Delete" /></a></td>';
        echo '</tr>';
    }
    ?>
    <tr<?php echo ($i%2)!=0?' class="odd"':''; ?>>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td><a href="Admin/Edit"><img src="content/images/admin/add.png" alt="New" /></a></td>
    </tr>
    </table>
</div>