<div id="download" class="page">
    <p class="center">
        <img src="content/images/smartphone/logo.png" alt="Take A Look Inside Logo" class="logo" />
    </p>
        
    <div>       
        <h2>What is 'Take A Look Inside'?</h2>
                                    
        <p>
            Ghent has all kinds of beautiful buildings. But sometimes they aren't accessible for visitors. 
            Don't you want to know what's behind the walls? 
            Go ahead and scan all the buildings on the map.
        </p>           
    </div>
          
    <div>
        <h2>Why should I download?</h2>
                 
        <article> 
            <span><img class="screen" src="content/images/screenshots/scr_movie-01.png" /></span>
            
            <p>Sniff the atmosphere from te inside by watching te video's.<p>
        </article>             
            
        <article> 
            <span><img class="screen" src="content/images/screenshots/scr_scan.png" /></span>
            
            <p>Scan all the QR-codes from within the app.<p>
        </article>
             
        <article>
            <span><img class="screen" src="content/images/screenshots/scr_home_menu.png" /></span>
            
            <p>Get a personal home screen with a Must See recomendation list, your own favorites and Look Laters and a list of all the buildings you've already scanned.</p>
        </article>                 
    </div>
      
    <div> 
        <h2>Where can I download?</h2>
        
        <p>
            <span class="google-play">
                <a href="#"><img src="content/images/px.gif" alt="test" /></a>
            </span>
        </p>
    </div>
</div>