<div id="download" class="page">
    <p class="center">
        <img src="content/images/smartphone/logo.png" alt="Take A Look Inside Logo" class="logo" />
    </p>
        
    <div>       
        <h2>What is 'Take A Look Inside'?</h2>
                                    
        <p>
            Ghent has all kinds of beautiful buildings. But sometimes they aren't accessible for visitors. 
            Don't you want to know what's behind the walls? 
            Go ahead and scan all the buildings on the map.
        </p>           
    </div>
          
    <div>
        <h2>Why should I download?</h2>
                 
        <article> 
            <span><img class="screen" src="content/images/desktop/video_preview.png" alt="Video" /></span>
            
            <p>
                Sniff the atmosphere from the inside by <em>watching the video's</em>.
            </p>
        </article>  
        
        <article>
            <span><img class="screen" src="content/images/desktop/menu_preview.png" alt="Screen" /></span>
            
            <p>
                Get a <em>personal home screen</em> with a Must See recomendation list, your own favorites, Look Laters and a list of all the buildings you've already scanned.
            </p>
        </article>            
            
        <article> 
            <span><img class="screen" src="content/images/desktop/scan_preview.png" alt="Scan" /></span>
            
            <p>
                <em>Scan</em> all the QR-codes from within the app.
            </p>
        </article>                
    </div>
      
    <div> 
        <h2>Where can I download?</h2>
        
        <p>
            <span class="google-play">
                <a href="#"><img src="content/images/px.gif" alt="test" /></a>
            </span>
        </p>
    </div>
</div>