<div id="credits" class="page">
    <p class="center">  
        <img src="content/images/smartphone/logo.png" alt="logo" class="logo">
    </p>
      
    <section id="what">                       
        <h1 class='titelcredits'> What is 'Take A Look Inside'? </h1>
                            
        <p id="whatis">
            Ghent has all kinds of beautiful buildings. But sometimes they aren't accessible for visitors. Don't you want to know what's behind the walls? 
            Go ahead and scan all the buildings on the map.
        </p>        
    </section>
        
    <div id="backgroundimg"></div>
        
        <div id='whobackground'>
            <section id="who">
                <h1 class="titelcredits"> Credits </h1>
                <div class="creditsblock">       
                    <p class="left">Developed by:</p>
                    <div class="right">                
                        <li>Lieven Benoot </li>
                        <li>Sam verschueren </li>
                    </div> 
                    <div class="clear"></div>
                 </div>
                <div class="creditsblock">      
                    <p class="left">Designed by:</p>
                    <div class="right">
                        <li>Nocolas Dierck</li>
                    </div>
                    <div class="clear"></div>   
                </div>           
                <div class="creditsblock">                        
                    <!--p class="full" id="isoc"> during iRail Summer of Code #iSoc12</p-->                      
                    <p class="left" id="filmed"> Filmed by: </p>
                    <div class="right" id="peter"> Peter De Bock </div>
                    <div class="clear"></div>
                </div>
                <div class="creditsblock">    
                    <p class="full">Developed under the name of CODE 9000 (#code9000) during iRail Summer of Code (#iSoc12) </p>
                    <div class="clear"></div> 
                </div >
                    
                <p class="full">Made possible by:</p>                    
                <div class="full" id="sponsors">                            
                    <a href="http://gent.be" target="_newtab"><img class="sponsorlogo" src="content/images/sponsors/gentzoveelstad.png"  alt="zoveelstad" /></a>
                    <a href="http://digipolis.be" target="_newtab"><img class="sponsorlogo" src="content/images/sponsors/digipolis-01.png"  alt="Digipolis" /> </a>
                    <a href="http://gent.be" target="_newtab"><img class="sponsorlogo" src="content/images/sponsors/stadgent.png"  alt="stadgent" /> </a>
                    <a href="http://hello.irail.be" target="_newtab"><img class="sponsorlogo" src="content/images/sponsors/iRail.png"  alt="iRail" /></a>                
                </div>        
         </section> 
        </div>



</div>