<div id="information" class="page">    
    
    <div id="creditsicon">
        <a href="Home/Credits"><img src="content/images/credits.png" alt="credits"></a>
    </div>
    
    <p class="center">
        <img src="content/images/smartphone/logo.png" alt="Take A Look Inside Logo" class="logo" />
    </p>
    
    <h1>AN EXPERIENCE INSIDE BEAUTIFUL BUILDINGS IN GHENT</h1>
    
    <h6>How?</h6>
    
    <p class="explanation">
        Scan the QR-codes in front of the buildings. You will get a glimps of the atmosphere inside.
    </p>    
</div>
