<div id="map" class="page">
    <input type="hidden" name="redirect" value="<?php echo $viewData["redirect"]; ?>" />
    
    <div id="header">
        <div id="fireFilterSection"> 
            <h3>
                <img id="legendarrow" src="content/images/legend-arrow.png" />
                
                Filter
            </h3>
        </div>
        <div id="filter" style="display: none;">
            <ul id="filterSection"></ul>
        </div>
    </div>
    
    <div id="mapButtons">
        <img id="routeToButton" class="rightMapButton" src="content/images/route.png" alt="Route" />
    </div>
    
    <div id="mapview"></div>    
</div>
